services:
  # Zookeeper (Required by Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # PostgreSQL Database
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transaction
      
  # Kafka UI (Web Interface for Kafka)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092

  yape.transactionservice.api:
    image: ${DOCKER_REGISTRY-}yapetransactionserviceapi
    build:
      context: .
      dockerfile: Yape.TransactionService.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:      
      - ConnectionStrings__YapeConnectionString=Host=127.0.0.1;Port=5432;Database=transaction;UserName=postgres;Password=postgres;Include Error Detail=true

  yape.transactionservice.worker:
    image: ${DOCKER_REGISTRY-}yapetransactionserviceworker
    build:
      context: .
      dockerfile: Yape.TransactionService.Worker/Dockerfile
    environment:      
      - ConnectionStrings__YapeConnectionString=Host=127.0.0.1;Port=5432;Database=transaction;UserName=postgres;Password=postgres;Include Error Detail=true
